### ISSUE TITLE
PHP7 won't install

### ISSUE THREAD

**Issue by thedamian** [skycocker/chromebrew#344]
What are you guys doing? 
I didn't check in that last PHP7 update without it wasn't installing.

Has anyone tried the PHP7 current package? It doesn't install on my fairly freshly installed chromebook pixel (64x intel)

Has anyone tried PHP7 ? and WHO MERGED IT!

**Comment by jam7** [comment]
What kind of errors are you having?

It worked fine on both flip (armv7l) and c202sa (x86_64) although it is required the latest pkgconfig from #341 for c202sa.

**Comment by uberhacker** [comment]
@thedamian: One thing I found out while testing that you need to remember to do is if you pull the latest changes from master in your working directory, you need to copy the packages directory contents into `/usr/local/lib/crew/packages`.  This really had me stumped awhile until it dawned on me.  What I do is the following:
```
$ cd /path/to/local/chromebrew
$ git pull origin master (This assumes you cloned the main repo, not your forked personal repo)
$ cp -r packages/ /usr/local/lib/crew/
$ crew install somepackage
```
I'm not sure if you ran across this situation ever, but it really bit me the first time I attempted package installation using the latest commits.

**Comment by lyxell** [comment]
It's working fine for numerous people, could you update chromebrew and submit an error log?

**Comment by lyxell** [comment]
Could it be that we're missing pkgconfig as a dependency for the php package?

**Comment by uberhacker** [comment]
@lyxell: I don't think so.  I never needed it on a fresh install.  FWIW, I have only had trouble uninstalling it in the past but with @jam7's awesome cleanup suggestion, it uninstalls fine now and removes all traces of residue.

**Comment by uberhacker** [comment]
I did notice that after I uninstall `zlibpkg`, the `--with-zlib` configure option complains so it looks that will need to be added as a dependency as well.

**Comment by uberhacker** [comment]
I'm going to retract everything I mentioned previously.  Both @lyxell and @thedamian were right!  This package was definitely broken.  Please reference #347 above which should fix this issue.

**Comment by thedamian** [comment]
I'm perfectly fine if it's working for others but not me. I'm talking only of the openssl option i. Php failing at the configure part.What I mean is that in the configure section of the crew nstall php7. After installing auccessfully the latest openssl.... I get a conplaint and it errors out that it can't find the openssl headers. (Or library)

I have of course copied both the openssl and the latest php7.rb but I can also do the crew update since you guys merged it into the master. 

Right now I believe it will not successfully install on a brand new chromebook setup.

I had recently formatted and started again as i usually have to since im wokring on getting all the packages needed for asp.net core. So i usualkt install a library that gives me aegmentation errors and simply reinstall my chromebook from a usb flash drive.

I did that about a week ago do ibelive if my chromebook pixel errors out about missing the openssl library (even tbouhh ihave 1.0.2j installed from the openssl that was checked in with this php7 package) then i believe we've  done a disservice to the future developers that use crew to install php7

**Comment by jam7** [comment]
@thedamian I'll explain about the situation.  As you noticed, php7 couldn't find openssl library on x86_64 but only x86_64 with pkg_config.  If you installed pkgconfig like what @uberhacker did accidentally, php7 could find openssl.  It is caused by openssl install path.  Openssl is installed into /usr/local/lib64 on x86_64 but pkg_config doesn't search under lib64 although pkgconfig does search under lib64.

Why your php7 with `--with-ssl` worked is just your php7 didn't search openssl.  It shows several message tyring to search SSL but fails and compiles without openssl.  However your php7 still could use openssl through curl library.

It's the story why many of us though php7 was configured correctly.  To fix your problem please performs following steps (removing both pkg_config and pkgconfig and install only pkgconfig to avoid any conflicts).
```
$ sudo crew remove pkg_config
$ sudo crew remove pkgconfig
$ crew install pkgconfig
$ crew install php7
```

In addition, pkgconfig and pkg_config had another story about conflicts.  previous pkgoconfig searched only lib64 and not lib.  pkg_config searches only lib and not lib64.  I updated pkgconfig to search both lib and lib64, so your asp.net core should work with only the latest pkgconfig.

**Comment by uberhacker** [comment]
@jam7, @thedamian: My latest PR #347 includes `pkgconfig` as a dependency, so you won't even need to install it prior to installing `php7` now.

**Comment by jam7** [comment]
Your PR is good.  But, having pkgconfig in dependency doesn't solve pkgconfig and pkg_config problem if pkg_config was already installed.  It's the reason why I explained like above.

**Comment by uberhacker** [comment]
Yeah, I suppose having `pkg_config` installed already would create an issue.  I imagine you might have the same problem if you installed `openssl_devel` and tried installing `openssl` afterwards?  If I'm understanding what you mentioned about `pkgconfig`, we can get rid of `pkg_config` now, correct?

**Comment by jam7** [comment]
@uberhacker I think so, but it is possible to discuss about it at #328 not here.

**Comment by lyxell** [comment]
@thedamian Can you try #347 out and see if this resolves the issue?

**Comment by thedamian** [comment]
It seems to be working. 
I erased (really reset) my .bash_profile and did a "crew remove openssl" so that I would test the official openssl in our system too.

**Comment by thedamian** [comment]
Completely installed on my chromebook pixel perfectly after using pull https://github.com/skycocker/chromebrew/pull/347

And then tested it successfully by installing composer which requires HTTPS

I'm testing it on my chromebook CR-48 but I feel it's worked flawless and has already passed the configure section that was giving me trouble before.

Great job!

**Comment by jam7** [comment]
glad to hear that.

**Comment by lyxell** [comment]
Great!

**Comment by uberhacker** [comment]
FWIW, I have already used PHP and Composer on my Chromebook to do actual work.  Nice having useful tool availables. :)
